### ISSUE TITLE
Azure pipeline failure, how to resolve

### ISSUE THREAD

**Issue by veghdev** [conda-forge/ipyvizzu-story-feedstock#5] opened 2022-08-05 06:42 UTC
### Comment:

@sugatoray  linux linux_64_ job failed because "nothing provides requested ipyvizzu".

Is this because ipyvizzu and iypvizzu-story recipes were created in the same [PR19838](https://github.com/conda-forge/staged-recipes/pull/19838) (and that point ipyvizzu is not available yet)?

If the answer is yes, can we fix it by sending a "please restart ci" command to conda forge admin?

**Comment by sugatoray** [comment] 2022-08-05 12:47
Yes, the root cause is what you guessed. 

Typically this is fixed with sending an empty commit to a new PR (no changes to the recipe).

**Closed as completed** 2022-08-05 18:08 UTC
Labels: question
